name: build

on: [push, pull_request]

jobs:
  build_ios:
    name: Build iOS on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run ${{ github.repository_owner }}/clang-format@shell
        run: |
          brew install clang-format
      - run: clang-format -style=file -i ios/Classes/*.h ios/Classes/*.m --dry-run
      - run: flutter --version
      - run: flutter pub get
      - run: flutter format --dry-run --set-exit-if-changed .
      - run: flutter pub publish --dry-run
      - run: flutter analyze lib example/lib
      - run: cd example; flutter build ios --no-codesign
